#!/usr/bin/env python3
"""Emit Ciji.xcodeproj/project.pbxproj (keeps IDs stable)."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PBX = ROOT / "Ciji.xcodeproj" / "project.pbxproj"

SWIFT_SOURCES = [
    ("main.swift", "Ciji/main.swift"),
    ("AppDelegate.swift", "Ciji/AppDelegate.swift"),
    ("CijiInputController.swift", "Ciji/CijiInputController.swift"),
    ("InputSession.swift", "Ciji/InputSession.swift"),
    ("CandidatePanel.swift", "Ciji/CandidatePanel.swift"),
    ("Pinyin.swift", "Ciji/Engine/Pinyin.swift"),
    ("Xiaohe.swift", "Ciji/Engine/Xiaohe.swift"),
    ("Lexicon.swift", "Ciji/Engine/Lexicon.swift"),
    ("Decoder.swift", "Ciji/Engine/Decoder.swift"),
    ("AppConfig.swift", "Ciji/Translation/AppConfig.swift"),
    ("GlossService.swift", "Ciji/Translation/GlossService.swift"),
]

RESOURCES = [
    ("cedict.tsv.gz", "Ciji/Resources/cedict.tsv.gz"),
    ("config.sample.json", "Ciji/Resources/config.sample.json"),
    ("ciji.icns", "Ciji/Resources/ciji.icns"),
    ("Assets.xcassets", "Ciji/Assets.xcassets"),
    ("InfoPlist.strings_zh", "Ciji/zh-Hans.lproj/InfoPlist.strings"),
    ("InfoPlist.strings_en", "Ciji/en.lproj/InfoPlist.strings"),
]


def hid(n: int) -> str:
    return f"A{n:023X}"


def main() -> None:
    file_ids = {}
    build_ids = {}
    n = 0x100
    for name, _ in SWIFT_SOURCES + RESOURCES:
        file_ids[name] = hid(n)
        n += 1
        build_ids[name] = hid(n)
        n += 1

    ids = {
        "project": hid(1),
        "main_group": hid(2),
        "products": hid(3),
        "ciji_group": hid(4),
        "engine_group": hid(5),
        "trans_group": hid(6),
        "res_group": hid(7),
        "zh_group": hid(8),
        "en_group": hid(9),
        "target": hid(0x10),
        "sources": hid(0x11),
        "frameworks": hid(0x12),
        "resources": hid(0x13),
        "proj_cfgs": hid(0x20),
        "tgt_cfgs": hid(0x21),
        "proj_debug": hid(0x22),
        "proj_release": hid(0x23),
        "tgt_debug": hid(0x24),
        "tgt_release": hid(0x25),
        "product": hid(0x30),
        "info_plist": hid(0x31),
        "entitlements": hid(0x32),
        "cocoa": hid(0x40),
        "imk": hid(0x41),
        "libz": hid(0x42),
        "cocoa_build": hid(0x43),
        "imk_build": hid(0x44),
        "libz_build": hid(0x45),
    }

    def fileref(name: str, path: str, kind: str) -> str:
        return f'\t\t{file_ids[name]} /* {path} */ = {{isa = PBXFileReference; lastKnownFileType = {kind}; path = {path.split("/")[-1]}; sourceTree = "<group>"; }};'

    lines = [
        "// !$*UTF8*$!",
        "{",
        "\tarchiveVersion = 1;",
        "\tclasses = {",
        "\t};",
        "\tobjectVersion = 56;",
        "\tobjects = {",
        "",
        "/* Begin PBXBuildFile section */",
    ]
    for name, path in SWIFT_SOURCES:
        lines.append(
            f"\t\t{build_ids[name]} /* {path} in Sources */ = {{isa = PBXBuildFile; fileRef = {file_ids[name]} /* {path} */; }};"
        )
    for name, path in RESOURCES:
        lines.append(
            f"\t\t{build_ids[name]} /* {path} in Resources */ = {{isa = PBXBuildFile; fileRef = {file_ids[name]} /* {path} */; }};"
        )
    lines += [
        f"\t\t{ids['cocoa_build']} /* Cocoa.framework in Frameworks */ = {{isa = PBXBuildFile; fileRef = {ids['cocoa']} /* Cocoa.framework */; }};",
        f"\t\t{ids['imk_build']} /* InputMethodKit.framework in Frameworks */ = {{isa = PBXBuildFile; fileRef = {ids['imk']} /* InputMethodKit.framework */; }};",
        f"\t\t{ids['libz_build']} /* libz.tbd in Frameworks */ = {{isa = PBXBuildFile; fileRef = {ids['libz']} /* libz.tbd */; }};",
        "/* End PBXBuildFile section */",
        "",
        "/* Begin PBXFileReference section */",
        f'\t\t{ids["product"]} /* Ciji.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = Ciji.app; sourceTree = BUILT_PRODUCTS_DIR; }};',
        f'\t\t{ids["info_plist"]} /* Info.plist */ = {{isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; }};',
        f'\t\t{ids["entitlements"]} /* Ciji.entitlements */ = {{isa = PBXFileReference; lastKnownFileType = text.plist.entitlements; path = Ciji.entitlements; sourceTree = "<group>"; }};',
        f'\t\t{ids["cocoa"]} /* Cocoa.framework */ = {{isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Cocoa.framework; path = System/Library/Frameworks/Cocoa.framework; sourceTree = SDKROOT; }};',
        f'\t\t{ids["imk"]} /* InputMethodKit.framework */ = {{isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = InputMethodKit.framework; path = System/Library/Frameworks/InputMethodKit.framework; sourceTree = SDKROOT; }};',
        f'\t\t{ids["libz"]} /* libz.tbd */ = {{isa = PBXFileReference; lastKnownFileType = "sourcecode.text-based-dylib-definition"; name = libz.tbd; path = usr/lib/libz.tbd; sourceTree = SDKROOT; }};',
    ]
    kinds = {
        ".swift": "sourcecode.swift",
        ".gz": "archive.gzip",
        ".json": "text.json",
        ".icns": "image.icns",
        ".xcassets": "folder.assetcatalog",
        ".strings": "text.plist.strings",
    }
    for name, path in SWIFT_SOURCES + RESOURCES:
        suffix = "." + path.split(".")[-1]
        if path.endswith(".xcassets"):
            suffix = ".xcassets"
        if path.endswith(".strings"):
            suffix = ".strings"
        if path.endswith(".tsv.gz"):
            suffix = ".gz"
        lines.append(fileref(name, path, kinds[suffix]))
    lines += [
        "/* End PBXFileReference section */",
        "",
        "/* Begin PBXFrameworksBuildPhase section */",
        f"\t\t{ids['frameworks']} /* Frameworks */ = {{",
        "\t\t\tisa = PBXFrameworksBuildPhase;",
        "\t\t\tbuildActionMask = 2147483647;",
        "\t\t\tfiles = (",
        f"\t\t\t\t{ids['cocoa_build']} /* Cocoa.framework in Frameworks */,",
        f"\t\t\t\t{ids['imk_build']} /* InputMethodKit.framework in Frameworks */,",
        f"\t\t\t\t{ids['libz_build']} /* libz.tbd in Frameworks */,",
        "\t\t\t);",
        "\t\t\trunOnlyForDeploymentPostprocessing = 0;",
        "\t\t};",
        "/* End PBXFrameworksBuildPhase section */",
        "",
        "/* Begin PBXGroup section */",
        f"\t\t{ids['main_group']} = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{ids['ciji_group']} /* Ciji */,",
        f"\t\t\t\t{ids['products']} /* Products */,",
        "\t\t\t);",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['products']} /* Products */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{ids['product']} /* Ciji.app */,",
        "\t\t\t);",
        "\t\t\tname = Products;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['ciji_group']} /* Ciji */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['main.swift']} /* main.swift */,",
        f"\t\t\t\t{file_ids['AppDelegate.swift']} /* AppDelegate.swift */,",
        f"\t\t\t\t{file_ids['CijiInputController.swift']} /* CijiInputController.swift */,",
        f"\t\t\t\t{file_ids['InputSession.swift']} /* InputSession.swift */,",
        f"\t\t\t\t{file_ids['CandidatePanel.swift']} /* CandidatePanel.swift */,",
        f"\t\t\t\t{ids['engine_group']} /* Engine */,",
        f"\t\t\t\t{ids['trans_group']} /* Translation */,",
        f"\t\t\t\t{ids['res_group']} /* Resources */,",
        f"\t\t\t\t{ids['zh_group']} /* zh-Hans.lproj */,",
        f"\t\t\t\t{ids['en_group']} /* en.lproj */,",
        f"\t\t\t\t{file_ids['Assets.xcassets']} /* Assets.xcassets */,",
        f"\t\t\t\t{ids['info_plist']} /* Info.plist */,",
        f"\t\t\t\t{ids['entitlements']} /* Ciji.entitlements */,",
        "\t\t\t);",
        "\t\t\tpath = Ciji;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['engine_group']} /* Engine */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['Pinyin.swift']} /* Pinyin.swift */,",
        f"\t\t\t\t{file_ids['Xiaohe.swift']} /* Xiaohe.swift */,",
        f"\t\t\t\t{file_ids['Lexicon.swift']} /* Lexicon.swift */,",
        f"\t\t\t\t{file_ids['Decoder.swift']} /* Decoder.swift */,",
        "\t\t\t);",
        "\t\t\tpath = Engine;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['trans_group']} /* Translation */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['AppConfig.swift']} /* AppConfig.swift */,",
        f"\t\t\t\t{file_ids['GlossService.swift']} /* GlossService.swift */,",
        "\t\t\t);",
        "\t\t\tpath = Translation;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['res_group']} /* Resources */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['cedict.tsv.gz']} /* cedict.tsv.gz */,",
        f"\t\t\t\t{file_ids['config.sample.json']} /* config.sample.json */,",
        f"\t\t\t\t{file_ids['ciji.icns']} /* ciji.icns */,",
        "\t\t\t);",
        "\t\t\tpath = Resources;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['zh_group']} /* zh-Hans.lproj */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['InfoPlist.strings_zh']} /* InfoPlist.strings */,",
        "\t\t\t);",
        "\t\t\tpath = \"zh-Hans.lproj\";",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        f"\t\t{ids['en_group']} /* en.lproj */ = {{",
        "\t\t\tisa = PBXGroup;",
        "\t\t\tchildren = (",
        f"\t\t\t\t{file_ids['InfoPlist.strings_en']} /* InfoPlist.strings */,",
        "\t\t\t);",
        "\t\t\tpath = en.lproj;",
        '\t\t\tsourceTree = "<group>";',
        "\t\t};",
        "/* End PBXGroup section */",
        "",
        "/* Begin PBXNativeTarget section */",
        f"\t\t{ids['target']} /* Ciji */ = {{",
        "\t\t\tisa = PBXNativeTarget;",
        "\t\t\tbuildConfigurationList = %s /* Build configuration list for PBXNativeTarget \"Ciji\" */;" % ids["tgt_cfgs"],
        "\t\t\tbuildPhases = (",
        f"\t\t\t\t{ids['sources']} /* Sources */,",
        f"\t\t\t\t{ids['frameworks']} /* Frameworks */,",
        f"\t\t\t\t{ids['resources']} /* Resources */,",
        "\t\t\t);",
        "\t\t\tbuildRules = (",
        "\t\t\t);",
        "\t\t\tdependencies = (",
        "\t\t\t);",
        "\t\t\tname = Ciji;",
        "\t\t\tproductName = Ciji;",
        f"\t\t\tproductReference = {ids['product']} /* Ciji.app */;",
        '\t\t\tproductType = "com.apple.product-type.application";',
        "\t\t};",
        "/* End PBXNativeTarget section */",
        "",
        "/* Begin PBXProject section */",
        f"\t\t{ids['project']} /* Project object */ = {{",
        "\t\t\tisa = PBXProject;",
        "\t\t\tattributes = {",
        "\t\t\t\tBuildIndependentTargetsInParallel = 1;",
        '\t\t\t\tLastSwiftUpdateCheck = 1500;',
        "\t\t\t\tLastUpgradeCheck = 1500;",
        "\t\t\t};",
        f"\t\t\tbuildConfigurationList = {ids['proj_cfgs']} /* Build configuration list for PBXProject \"Ciji\" */;",
        '\t\t\tcompatibilityVersion = "Xcode 14.0";',
        "\t\t\tdevelopmentRegion = \"zh-Hans\";",
        "\t\t\thasScannedForEncodings = 0;",
        "\t\t\tknownRegions = (",
        "\t\t\t\ten,",
        "\t\t\t\tBase,",
        "\t\t\t\t\"zh-Hans\",",
        "\t\t\t);",
        f"\t\t\tmainGroup = {ids['main_group']};",
        "\t\t\tproductRefGroup = %s /* Products */;" % ids["products"],
        '\t\t\tprojectDirPath = "";',
        '\t\t\tprojectRoot = "";',
        "\t\t\ttargets = (",
        f"\t\t\t\t{ids['target']} /* Ciji */,",
        "\t\t\t);",
        "\t\t};",
        "/* End PBXProject section */",
        "",
        "/* Begin PBXResourcesBuildPhase section */",
        f"\t\t{ids['resources']} /* Resources */ = {{",
        "\t\t\tisa = PBXResourcesBuildPhase;",
        "\t\t\tbuildActionMask = 2147483647;",
        "\t\t\tfiles = (",
    ]
    for name, path in RESOURCES:
        lines.append(f"\t\t\t\t{build_ids[name]} /* {path} in Resources */,")
    lines += [
        "\t\t\t);",
        "\t\t\trunOnlyForDeploymentPostprocessing = 0;",
        "\t\t};",
        "/* End PBXResourcesBuildPhase section */",
        "",
        "/* Begin PBXSourcesBuildPhase section */",
        f"\t\t{ids['sources']} /* Sources */ = {{",
        "\t\t\tisa = PBXSourcesBuildPhase;",
        "\t\t\tbuildActionMask = 2147483647;",
        "\t\t\tfiles = (",
    ]
    for name, path in SWIFT_SOURCES:
        lines.append(f"\t\t\t\t{build_ids[name]} /* {path} in Sources */,")
    lines += [
        "\t\t\t);",
        "\t\t\trunOnlyForDeploymentPostprocessing = 0;",
        "\t\t};",
        "/* End PBXSourcesBuildPhase section */",
        "",
        "/* Begin XCBuildConfiguration section */",
        f"\t\t{ids['proj_debug']} /* Debug */ = {{",
        "\t\t\tisa = XCBuildConfiguration;",
        "\t\t\tbuildSettings = {",
        "\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;",
        "\t\t\t\tCLANG_ENABLE_MODULES = YES;",
        "\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;",
        "\t\t\t\tCOPY_PHASE_STRIP = NO;",
        "\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;",
        "\t\t\t\tENABLE_TESTABILITY = YES;",
        "\t\t\t\tGCC_DYNAMIC_NO_PIC = NO;",
        "\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 13.0;",
        "\t\t\t\tONLY_ACTIVE_ARCH = YES;",
        "\t\t\t\tSDKROOT = macosx;",
        "\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;",
        "\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-Onone\";",
        "\t\t\t\tSWIFT_VERSION = 5.0;",
        "\t\t\t};",
        '\t\t\tname = Debug;',
        "\t\t};",
        f"\t\t{ids['proj_release']} /* Release */ = {{",
        "\t\t\tisa = XCBuildConfiguration;",
        "\t\t\tbuildSettings = {",
        "\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;",
        "\t\t\t\tCLANG_ENABLE_MODULES = YES;",
        "\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;",
        "\t\t\t\tDEBUG_INFORMATION_FORMAT = \"dwarf-with-dsym\";",
        "\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 13.0;",
        "\t\t\t\tSDKROOT = macosx;",
        "\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;",
        "\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-O\";",
        "\t\t\t\tSWIFT_VERSION = 5.0;",
        "\t\t\t};",
        '\t\t\tname = Release;',
        "\t\t};",
        f"\t\t{ids['tgt_debug']} /* Debug */ = {{",
        "\t\t\tisa = XCBuildConfiguration;",
        "\t\t\tbuildSettings = {",
        "\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;",
        "\t\t\t\tCODE_SIGN_IDENTITY = \"-\";",
        "\t\t\t\tCODE_SIGN_STYLE = Manual;",
        "\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;",
        "\t\t\t\tCURRENT_PROJECT_VERSION = 1;",
        "\t\t\t\tENABLE_HARDENED_RUNTIME = NO;",
        "\t\t\t\tGENERATE_INFOPLIST_FILE = NO;",
        "\t\t\t\tINFOPLIST_FILE = Ciji/Info.plist;",
        "\t\t\t\tLD_RUNPATH_SEARCH_PATHS = \"$(inherited) @executable_path/../Frameworks\";",
        "\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 13.0;",
        "\t\t\t\tMARKETING_VERSION = 1.0.0;",
        '\t\t\t\tOTHER_LDFLAGS = "$(inherited) -lz";',
        "\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.shengtao.ciji.inputmethod;",
        "\t\t\t\tPRODUCT_NAME = Ciji;",
        "\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;",
        "\t\t\t\tSWIFT_VERSION = 5.0;",
        "\t\t\t};",
        '\t\t\tname = Debug;',
        "\t\t};",
        f"\t\t{ids['tgt_release']} /* Release */ = {{",
        "\t\t\tisa = XCBuildConfiguration;",
        "\t\t\tbuildSettings = {",
        "\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;",
        "\t\t\t\tCODE_SIGN_IDENTITY = \"-\";",
        "\t\t\t\tCODE_SIGN_STYLE = Manual;",
        "\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;",
        "\t\t\t\tCURRENT_PROJECT_VERSION = 1;",
        "\t\t\t\tENABLE_HARDENED_RUNTIME = NO;",
        "\t\t\t\tGENERATE_INFOPLIST_FILE = NO;",
        "\t\t\t\tINFOPLIST_FILE = Ciji/Info.plist;",
        "\t\t\t\tLD_RUNPATH_SEARCH_PATHS = \"$(inherited) @executable_path/../Frameworks\";",
        "\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 13.0;",
        "\t\t\t\tMARKETING_VERSION = 1.0.0;",
        '\t\t\t\tOTHER_LDFLAGS = "$(inherited) -lz";',
        "\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.shengtao.ciji.inputmethod;",
        "\t\t\t\tPRODUCT_NAME = Ciji;",
        "\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;",
        "\t\t\t\tSWIFT_VERSION = 5.0;",
        "\t\t\t};",
        '\t\t\tname = Release;',
        "\t\t};",
        "/* End XCBuildConfiguration section */",
        "",
        "/* Begin XCConfigurationList section */",
        f"\t\t{ids['proj_cfgs']} /* Build configuration list for PBXProject \"Ciji\" */ = {{",
        "\t\t\tisa = XCConfigurationList;",
        "\t\t\tbuildConfigurations = (",
        f"\t\t\t\t{ids['proj_debug']} /* Debug */,",
        f"\t\t\t\t{ids['proj_release']} /* Release */,",
        "\t\t\t);",
        "\t\t\tdefaultConfigurationIsVisible = 0;",
        "\t\t\tdefaultConfigurationName = Release;",
        "\t\t};",
        f"\t\t{ids['tgt_cfgs']} /* Build configuration list for PBXNativeTarget \"Ciji\" */ = {{",
        "\t\t\tisa = XCConfigurationList;",
        "\t\t\tbuildConfigurations = (",
        f"\t\t\t\t{ids['tgt_debug']} /* Debug */,",
        f"\t\t\t\t{ids['tgt_release']} /* Release */,",
        "\t\t\t);",
        "\t\t\tdefaultConfigurationIsVisible = 0;",
        "\t\t\tdefaultConfigurationName = Release;",
        "\t\t};",
        "/* End XCConfigurationList section */",
        "\t};",
        f"\trootObject = {ids['project']} /* Project object */;",
        "}",
        "",
    ]
    PBX.parent.mkdir(parents=True, exist_ok=True)
    PBX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {PBX}")


if __name__ == "__main__":
    main()
